{% set name = "robotframework-datadriver" %}
{% set version = "1.7.0" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 227fcda24d7726c63584d5a454f736f6e9bd3f922b8fad687d8779504092933b
  # TODO: upstream PR
  - fn: README.rst
    url: https://raw.githubusercontent.com/Snooz82/{{ name }}/{{ version }}/Readme.rst
    sha256: 0f94123b7e1acb509e15e17ee3cf6bd84b8ea53c292c2cf8cae83d884b226fc7

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "TBD"

outputs:
  - name: {{ name }}
    build:
      number: {{ build_number }}
      noarch: python
      script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - docutils
        - pygments
        - python >=3.6
        - robotframework >=3.1

    test:
      imports:
        - DataDriver
        - DataDriver.csv_reader
        - DataDriver.json_reader
        - DataDriver.pict_reader
      commands:
        - pip check
      requires:
        - pip

    about:
      home: https://github.com/Snooz82/robotframework-datadriver
      summary: A library for Data-Driven Testing.
      license: Apache-2.0
      license_file:
        - COPYRIGHT.txt
        - LICENSE


  - name: {{ name }}-with-xls
    build:
      number: {{ build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ name }} {{ version }}.*
        - pandas
        - xlrd >=1.2.0
        - openpyxl
    test:
      imports:
        - DataDriver.xls_reader
        - DataDriver.xlsx_reader
      commands:
        - pip check
      requires:
        - pip

    about:
      home: https://github.com/Snooz82/robotframework-datadriver
      summary: A library for Data-Driven Testing. (with Excel support)
      license: Apache-2.0
      license_file:
        - COPYRIGHT.txt
        - LICENSE

about:
  home: https://github.com/Snooz82/robotframework-datadriver
  summary: A library for Data-Driven Testing.
  license: Apache-2.0
  license_file:
    - COPYRIGHT.txt
    - LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
