{% set version = "1.8.0" %}

package:
  name: robotframework-datadriver-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-datadriver/robotframework-datadriver-{{ version }}.tar.gz
  sha256: 6ff2f9fb23b7171a65e08965b14e591727b0eb746cab44d9dd7330ab7edcfd55

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7.12
  run:
    - python >=3.7.12

outputs:
  - name: robotframework-datadriver
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
    requirements:
      host:
        - pip
        - python >=3.7.12
      run:
        - docutils
        - pygments
        - python >=3.7.12
        - robotframework >=4.0.2

    test:
      imports:
        - DataDriver
        - DataDriver.csv_reader
        - DataDriver.json_reader
        - DataDriver.pict_reader
      commands:
        - pip check
      requires:
        - pip

    about:
      home: https://github.com/Snooz82/robotframework-datadriver
      summary: A library for Data-Driven Testing.
      license: Apache-2.0
      license_file:
        - COPYRIGHT.txt
        - LICENSE


  - name: robotframework-datadriver-with-xls
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7.12
      run:
        - {{ pin_subpackage('robotframework-datadriver', max_pin='x.x.x') }}
        - openpyxl
        - pandas
        - python >=3.7.12
        - xlrd >=1.2.0
    test:
      imports:
        - DataDriver.xls_reader
        - DataDriver.xlsx_reader
      commands:
        - pip check
      requires:
        - pip

    about:
      home: https://github.com/Snooz82/robotframework-datadriver
      summary: A library for Data-Driven Testing. (with Excel support)
      license: Apache-2.0
      license_file:
        - COPYRIGHT.txt
        - LICENSE

about:
  home: https://github.com/Snooz82/robotframework-datadriver
  summary: A library for Data-Driven Testing.
  license: Apache-2.0
  license_file:
    - COPYRIGHT.txt
    - LICENSE

extra:
  feedstock-name: robotframework-datadriver
  recipe-maintainers:
    - bollwyvl
