{% set version = "1.11.2" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: robotframework-datadriver
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-datadriver/robotframework_datadriver-{{ version }}.tar.gz
  sha256: c75a3b8856e141331e65a22a6bed1a8263221ee6dad821d526f932918576fffd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed --no-build-isolation .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - docutils
    - pygments
    - python >={{ python_min }}
    - robotframework >=4.0.2, <8

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - DataDriver
    - DataDriver.csv_reader
    - DataDriver.json_reader
    - DataDriver.pict_reader
  commands:
    - pip check

outputs:
  - name: robotframework-datadriver

  - name: robotframework-datadriver-with-xls
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('robotframework-datadriver', max_pin='x.x.x') }}
        - openpyxl
        - pandas
        - xlrd >=1.2.0
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - DataDriver.xls_reader
        - DataDriver.xlsx_reader
      commands:
        - pip check

    about:
      home: https://github.com/Snooz82/robotframework-datadriver
      summary: A library for Data-Driven Testing. (with Excel support)
      license: Apache-2.0
      license_file:
        - COPYRIGHT.txt
        - LICENSE

about:
  home: https://github.com/Snooz82/robotframework-datadriver
  summary: A library for Data-Driven Testing.
  license: Apache-2.0
  license_file:
    - COPYRIGHT.txt
    - LICENSE

extra:
  feedstock-name: robotframework-datadriver
  recipe-maintainers:
    - bollwyvl
